const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const years = [
  "2000",
  "2001",
  "2002",
  "2003",
  "2004",
  "2005",
  "2006",
  "2007",
  "2008",
  "2009",
  "2010",
  "2011",
  "2012",
  "2013",
  "2014",
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
  "2024",
  "2025",
  "2026",
  "2027",
  "2028",
  "2029",
  "2030",
  "2031",
  "2032",
  "2033",
  "2034",
  "2035",
  "2036",
  "2037",
];

const hours = Array.from({ length: 12 }, (_, i) => i + 1);
const minutes = Array.from({ length: 60 }, (_, i) => i);

const programmingSkills = [
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "HTML",
  "CSS",
  "TypeScript",
  "SQL",
  "NoSQL",
  "React",
  "Angular",
  "Vue.js",
  "Next.js",
  "Node.js",
  "Django",
  "Flask",
  "Express.js",
  "Spring Boot",
  "Laravel",
  "Ruby on Rails",
  "ASP.NET",
  "GraphQL",
  "REST APIs",
  "WebRTC",
  "WebSockets",
  "Redux",
  "Prisma",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Webpack",
  "Babel",
  "Git",
  "GitHub",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "CI/CD",
  "AWS",
  "Azure",
  "Google Cloud",
  "Firebase",
  "Heroku",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Blockchain",
  "Solidity",
  "Smart Contracts",
  "Ethereum",
  "Web3.js",
  "Ethers.js",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Data Science",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Seaborn",
  "Power BI",
  "Tableau",
  "Jupyter Notebook",
  "Algorithms",
  "Data Structures",
  "Unit Testing",
  "Integration Testing",
  "End-to-End Testing",
  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Selenium",
  "Agile Methodology",
  "Scrum",
  "Object-Oriented Programming",
  "Functional Programming",
  "Mobile Development",
  "React Native",
  "Flutter",
  "Xamarin",
  "iOS Development",
  "Android Development",
  "UI/UX Design",
  "Figma",
  "Adobe XD",
  "RESTful APIs",
  "Microservices",
  "Serverless Architecture",
];

const hobbies = [
  "Reading",
  "Writing",
  "Drawing",
  "Painting",
  "Sculpting",
  "Photography",
  "Cooking",
  "Baking",
  "Gardening",
  "Fishing",
  "Hiking",
  "Camping",
  "Cycling",
  "Running",
  "Swimming",
  "Yoga",
  "Meditation",
  "Knitting",
  "Crocheting",
  "Sewing",
  "Woodworking",
  "Pottery",
  "Calligraphy",
  "Playing musical instruments",
  "Singing",
  "Dancing",
  "Acting",
  "Watching movies",
  "Playing video games",
  "Collecting stamps",
  "Collecting coins",
  "Bird watching",
  "Star gazing",
  "Traveling",
  "Blogging",
  "Vlogging",
  "Podcasting",
  "Learning languages",
  "Volunteering",
  "Martial arts",
  "Chess",
  "Board games",
  "Puzzle solving",
  "DIY crafts",
  "Origami",
  "Scrapbooking",
  "Robotics",
  "Coding",
  "3D printing",
  "Role-playing games",
  "Magic tricks",
  "Fitness training",
  "Weightlifting",
  "Bowling",
  "Archery",
  "Surfing",
  "Skiing",
  "Snowboarding",
  "Skating",
  "Playing soccer",
  "Playing basketball",
  "Playing tennis",
  "Playing badminton",
  "Golfing",
  "Playing cricket",
  "Listening to music",
  "Writing poetry",
  "Exploring nature",
  "Rock climbing",
  "Learning history",
  "Sketching",
  "Journaling",
  "Making jewelry",
  "Watching documentaries",
  "Home brewing",
  "Mixology",
  "Aquascaping",
  "Restoring furniture",
  "Decorating interiors",
  "Gaming (eSports)",
  "Fantasy sports",
  "Cosplaying",
  "Shopping",
  "Speed cubing",
  "Parkour",
  "Lego building",
  "Geocaching",
  "Urban exploration",
  "Zumba",
  "Pet training",
  "Horseback riding",
  "Flying drones",
  "Beekeeping",
  "Tattoo designing",
];

export { MONTHS, years, hours, minutes };
